/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm_quanly_cuahangbanh;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lyhoa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Tai_DS_Ban();
        Tai_DS_Banh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_chonban = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btn_trangchinh = new javax.swing.JButton();
        btn_quanlykho = new javax.swing.JButton();
        btn_quanlytaikhoan = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_goimon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_tenbanh = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btn_hoantat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        spinner_soluong1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lb_maban = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_banh = new javax.swing.JLabel();
        txt_soluongconlai = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_danhsachdagoi = new javax.swing.JTable();
        btn_xoakhoidanhsach = new javax.swing.JButton();
        btn_thanhtoan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_sotienthanhtoan = new javax.swing.JTextField();
        txt_sotiennhan = new javax.swing.JTextField();
        txt_sotienthua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_ban = new javax.swing.JLabel();
        btn_lammoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phần mềm quản lý bán hàng cửa hàng bánh ngọt");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Chọn bàn");

        tb_chonban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số bàn", "Tình trạng"
            }
        ));
        tb_chonban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_chonbanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_chonban);
        if (tb_chonban.getColumnModel().getColumnCount() > 0) {
            tb_chonban.getColumnModel().getColumn(0).setHeaderValue("Số bàn");
            tb_chonban.getColumnModel().getColumn(1).setHeaderValue("Tình trạng");
        }

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btn_trangchinh.setBackground(new java.awt.Color(255, 255, 255));
        btn_trangchinh.setForeground(new java.awt.Color(0, 0, 0));
        btn_trangchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-home-24.png"))); // NOI18N
        btn_trangchinh.setText("Trang chính");
        btn_trangchinh.setFocusable(false);
        btn_trangchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trangchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trangchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trangchinh);

        btn_quanlykho.setBackground(new java.awt.Color(255, 255, 255));
        btn_quanlykho.setForeground(new java.awt.Color(0, 0, 0));
        btn_quanlykho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-warehouse-24.png"))); // NOI18N
        btn_quanlykho.setText("Quản lý kho");
        btn_quanlykho.setFocusable(false);
        btn_quanlykho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanlykho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanlykho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlykhoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanlykho);

        btn_quanlytaikhoan.setBackground(new java.awt.Color(255, 255, 255));
        btn_quanlytaikhoan.setForeground(new java.awt.Color(0, 0, 0));
        btn_quanlytaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-management-24.png"))); // NOI18N
        btn_quanlytaikhoan.setText("Quản lý tài khoản");
        btn_quanlytaikhoan.setFocusable(false);
        btn_quanlytaikhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanlytaikhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanlytaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlytaikhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanlytaikhoan);

        btn_dangxuat.setBackground(new java.awt.Color(255, 255, 255));
        btn_dangxuat.setForeground(new java.awt.Color(0, 0, 0));
        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-go-back-24.png"))); // NOI18N
        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.setFocusable(false);
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangxuat);

        jTabbedPane2.setBackground(java.awt.Color.lightGray);
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        tb_goimon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên bánh", "Giá tiền", "Mã"
            }
        ));
        tb_goimon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_goimonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_goimon);
        if (tb_goimon.getColumnModel().getColumnCount() > 0) {
            tb_goimon.getColumnModel().getColumn(0).setMinWidth(150);
            tb_goimon.getColumnModel().getColumn(1).setMinWidth(100);
            tb_goimon.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        jLabel4.setText("Tên bánh:");

        btn_tim.setBackground(java.awt.Color.lightGray);
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-search-26.png"))); // NOI18N
        btn_tim.setText("Tìm");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        jLabel5.setText("Số lượng còn lại:");

        btn_hoantat.setBackground(java.awt.Color.lightGray);
        btn_hoantat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-check-all-24.png"))); // NOI18N
        btn_hoantat.setText("Hoàn tất");
        btn_hoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoantatActionPerformed(evt);
            }
        });

        jLabel7.setText("Số lượng đặt:");

        spinner_soluong1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel6.setText("Bàn số:");

        lb_maban.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lb_maban.setEnabled(false);
        lb_maban.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("Bánh:");

        lb_banh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_banh.setEnabled(false);
        lb_banh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_soluongconlai.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6)
                        .addGap(59, 59, 59)
                        .addComponent(lb_maban, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tenbanh, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                            .addComponent(btn_tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hoantat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(spinner_soluong1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(48, 48, 48)
                                        .addComponent(txt_soluongconlai, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_banh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_tenbanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_maban, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_banh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_soluongconlai, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spinner_soluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hoantat, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Gọi món", jPanel2);

        tb_danhsachdagoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên bánh", "Số lượng", "Giá tiền", "Mã bánh"
            }
        ));
        jScrollPane5.setViewportView(tb_danhsachdagoi);
        if (tb_danhsachdagoi.getColumnModel().getColumnCount() > 0) {
            tb_danhsachdagoi.getColumnModel().getColumn(0).setMinWidth(200);
            tb_danhsachdagoi.getColumnModel().getColumn(2).setMinWidth(150);
        }

        btn_xoakhoidanhsach.setBackground(java.awt.Color.lightGray);
        btn_xoakhoidanhsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-delete-bin-24.png"))); // NOI18N
        btn_xoakhoidanhsach.setText("Xóa  khỏi danh sách");
        btn_xoakhoidanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoakhoidanhsachActionPerformed(evt);
            }
        });

        btn_thanhtoan.setBackground(java.awt.Color.lightGray);
        btn_thanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-print-24.png"))); // NOI18N
        btn_thanhtoan.setText("Thanh toán");
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Số tiền nhận:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Số tiền thừa:");

        txt_sotienthanhtoan.setEditable(false);

        txt_sotienthua.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setText("Bàn số:");
        jLabel13.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel13InputMethodTextChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Số tiền thanh toán:");

        lb_ban.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lb_ban.setText("0");
        lb_ban.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lb_banInputMethodTextChanged(evt);
            }
        });

        btn_lammoi.setBackground(java.awt.Color.lightGray);
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-check-all-24.png"))); // NOI18N
        btn_lammoi.setText("Xác nhận");
        btn_lammoi.setEnabled(false);
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_ban))
                            .addComponent(btn_xoakhoidanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_sotiennhan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_sotienthanhtoan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_sotienthua)
                            .addComponent(btn_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoakhoidanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_sotienthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sotiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sotienthua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lammoi))
                    .addComponent(btn_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Danh sách đã gọi", jPanel4);

        jLabel8.setText("Chọn thao tác:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Tai_Dagoi(int soban) {
        DefaultTableModel DanhSachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
        float thanhtien = 0;
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("select tenbanh,sum(soluong)as soluong,giaban*sum(soluong) as thanhtoan, ban_banh.mabanh\n"
                        + "from banh,ban_banh\n"
                        + "where banh.mabanh = ban_banh.mabanh and soban = " + soban + "\n"
                        + "group by tenbanh,giaban, ban_banh.mabanh");
                while (kq.next()) {
                    String tenbanh = kq.getString(1);
                    int soluong = kq.getInt(2);
                    Float giatien = kq.getFloat(3);
                    String mabanh = kq.getString(4);
                    thanhtien = thanhtien + giatien;
                    DanhSachdagoi.addRow(new Object[]{tenbanh, soluong, giatien, mabanh});
                }

            }

        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
        txt_sotienthanhtoan.setText(String.valueOf(thanhtien));

    }

    public void Tai_DS_Ban() {
        DefaultTableModel DanhSachBan = (DefaultTableModel) tb_chonban.getModel();
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select soban, tinhtrang from ban");
                while (kq.next()) {
                    int soban = kq.getInt(1);
                    String tinhtrang = kq.getString(2);

                    DanhSachBan.addRow(new Object[]{soban, tinhtrang});
                }

            }

        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }

    public void loi_chucvu1() {
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select chucvu,tinhtrang from taikhoan where idnhanvien = '" + DangNhap.ID + "' ");
                while (kq.next()) {
                    String chucvu = kq.getString(1);
                    String tinhtrang = kq.getString(2);

                    if (chucvu.equals("Quản lý") && tinhtrang.trim().equals("Active")) {
                        Menu.this.setVisible(false);
                        new Quanlytaikhoan().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Phải đăng nhập bằng tài khoản quản lý!", "Thông báo", JOptionPane.ERROR_MESSAGE);

                    }
                }
            }
        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }

    public void loi_chucvu2() {
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select chucvu,tinhtrang from taikhoan where idnhanvien = '" + DangNhap.ID + "' ");
                while (kq.next()) {
                    String chucvu = kq.getString(1);
                    String tinhtrang = kq.getString(2);

                    if (chucvu.equals("Quản lý") && tinhtrang.trim().equals("Active")) {
                        Menu.this.setVisible(false);
                        new Quanlykho().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Phải đăng nhập bằng tài khoản quản lý!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }

    public void Tai_DS_Banh() {
        DefaultTableModel DanhSachBanh = (DefaultTableModel) tb_goimon.getModel();
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select tenbanh,giaban,mabanh from banh");
                while (kq.next()) {
                    String tenbanh = kq.getString(1);
                    int giaban = kq.getInt(2);
                    String mabanh = kq.getString(3);
                    DanhSachBanh.addRow(new Object[]{tenbanh, giaban, mabanh});
                }
            }
        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }
    private void btn_quanlytaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlytaikhoanActionPerformed
        // TODO add your handling code here:
        loi_chucvu1();
    }//GEN-LAST:event_btn_quanlytaikhoanActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        // TODO add your handling code here:
        Menu.this.setVisible(false);
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_trangchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchinhActionPerformed
        // TODO add your handling code here:
        Menu.this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_btn_trangchinhActionPerformed

    private void btn_quanlykhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlykhoActionPerformed
        // TODO add your handling code here:

        loi_chucvu2();
    }//GEN-LAST:event_btn_quanlykhoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Thoát phần mềm?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbn = (DefaultTableModel) tb_goimon.getModel();
        String getTen = txt_tenbanh.getText();
        tbn.setRowCount(0);
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet rs = dd.executeQuery("select tenbanh,giaban,mabanh from banh where tenbanh like N'%" + getTen + "%' or mabanh like N'%" + getTen + "%'");

            while (rs.next()) {
                String tenbanh = rs.getString(1);
                int giaban = rs.getInt(2);
                String mabanh = rs.getString(3);
                tbn.addRow(new Object[]{tenbanh, giaban, mabanh});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_timActionPerformed

    private void tb_goimonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_goimonMouseClicked
        // TODO add your handling code here:
        spinner_soluong1.setValue(0);
        int Row = tb_goimon.getSelectedRow();
        String mabanh = (String) tb_goimon.getValueAt(Row, 2);
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select soluongconlai,tenbanh from banh where mabanh = " + mabanh + "");
                while (kq.next()) {
                    txt_soluongconlai.setText(kq.getString(1));
                    lb_banh.setText(kq.getString(2));

                }

            }

        } catch (Exception ex) {
            System.out.print(ex.toString());
        }

    }//GEN-LAST:event_tb_goimonMouseClicked

    public boolean ktban(String mabanh, int maban) {
        boolean kt = false;
        String banh = "";
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select mabanh from ban_banh where mabanh = '" + mabanh + "' and soban = " + maban + "");
                while (kq.next()) {
                    banh = kq.getString(1);
                }

            }
            if (banh.equals("")) {
                kt = true;
            } else {
                kt = false;
            }
            return kt;
        } catch (Exception ex) {
            System.out.print(ex.toString());
            return kt;
        }

    }
    public int soluongnhap(String mabanh, int maban) {
        int soluong = 0;

        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select soluong from ban_banh where mabanh = " + mabanh + " and soban = "+maban+"");
                while (kq.next()) {
                    soluong = kq.getInt(1);
                }

            }
            return soluong;
        } catch (Exception ex) {
            System.out.print(ex.toString());
            return soluong;
        }

    }
    private void btn_hoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoantatActionPerformed
        // TODO add your handling code here:

        try {
            int soluong = (int) spinner_soluong1.getValue();

            int Row = tb_chonban.getSelectedRow();
            int maban = (int) tb_chonban.getValueAt(Row, 0);
            try {
                int Row1 = tb_goimon.getSelectedRow();
                String mabanh = (String) tb_goimon.getValueAt(Row1, 2);

                try {

                    int soluongcon = Integer.parseInt(txt_soluongconlai.getText());
                    if (soluongcon <= 0) {
                        JOptionPane.showMessageDialog(null, "Hết bánh!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else if (soluong <= 0) {
                        JOptionPane.showMessageDialog(null, "Số lượng đặt phải lớn hơn 0!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else if (soluong > soluongcon) {
                        JOptionPane.showMessageDialog(null, "Không đủ bánh!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {

                        Connect a = new Connect();
                        Connection conn = a.getConnection();
                        if (conn != null) {
                            Statement dd = conn.createStatement();

                            if (ktban(mabanh, maban) == false) {
                                int sl = soluong + soluongnhap(mabanh,maban);
                                dd.executeUpdate("update ban_banh set soluong = "+sl+" where mabanh = '"+mabanh+"' and soban = "+maban+"");
                                JOptionPane.showMessageDialog(null, "Gọi món thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                int soluongcapnhat = soluongcon - soluong;
                                dd.executeUpdate("update banh set soluongconlai = " + soluongcapnhat + " where mabanh = '" + mabanh + "'  ");
                                dd.executeUpdate("update ban set tinhtrang = 'CÓ KHÁCH' where soban = '" + maban + "'  ");
                            } else {

                                dd.executeUpdate("insert into ban_banh (soban,mabanh,soluong) values ( '" + maban + "','" + mabanh + "'," + soluong + "  )   ");
                                JOptionPane.showMessageDialog(null, "Gọi món thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                int soluongcapnhat = soluongcon - soluong;
                                dd.executeUpdate("update banh set soluongconlai = " + soluongcapnhat + " where mabanh = '" + mabanh + "'  ");
                                dd.executeUpdate("update ban set tinhtrang = 'CÓ KHÁCH' where soban = '" + maban + "'  ");
                            }
                            DefaultTableModel danhsachban = (DefaultTableModel) tb_chonban.getModel();
                            DefaultTableModel danhsachbanh = (DefaultTableModel) tb_goimon.getModel();
                            danhsachban.setRowCount(0);
                            danhsachbanh.setRowCount(0);
                            Tai_DS_Ban();
                            Tai_DS_Banh();
                            lb_maban.setText("");
                            lb_banh.setText("");
                            txt_soluongconlai.setText("");
                            spinner_soluong1.setValue(0);
                        }
                    }
                } catch (Exception ex) {
                    System.out.print(ex.toString());
                    JOptionPane.showMessageDialog(null, "lỗi!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Chưa chọn bánh!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chưa chọn bàn!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_hoantatActionPerformed

    private void tb_chonbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_chonbanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel DanhSachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
        DanhSachdagoi.setRowCount(0);
        try {
            int Row = tb_chonban.getSelectedRow();
            int maban = (int) tb_chonban.getValueAt(Row, 0);
            lb_maban.setText(String.valueOf(maban));
            lb_ban.setText(String.valueOf(maban));
            Tai_Dagoi(maban);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chưa chọn bàn!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tb_chonbanMouseClicked

    private void jLabel13InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel13InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13InputMethodTextChanged

    private void lb_banInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lb_banInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_banInputMethodTextChanged


    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
        // TODO add your handling code here:
        try {
            int Row = tb_chonban.getSelectedRow();
            int maban = (int) tb_chonban.getValueAt(Row, 0);

            if (Float.parseFloat(txt_sotienthanhtoan.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Không có gì để thanh toán!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (txt_sotiennhan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập số tiền khách trả!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (Quanlykho.loi_kytu(txt_sotiennhan.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Phải nhập giá tiền bằng số!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (Float.parseFloat(txt_sotiennhan.getText()) < Float.parseFloat(txt_sotienthanhtoan.getText())) {
                JOptionPane.showMessageDialog(null, "Thiếu tiền!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                float tien = Float.parseFloat(txt_sotiennhan.getText()) - Float.parseFloat(txt_sotienthanhtoan.getText());
                txt_sotienthua.setText(String.valueOf(tien));
                btn_lammoi.setEnabled(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chưa chọn bàn", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    public int soluongne(String mabanh) {
        int soluong = 0;

        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select soluongconlai from banh where mabanh = " + mabanh + "");
                while (kq.next()) {
                    soluong = kq.getInt(1);
                }

            }
            return soluong;
        } catch (Exception ex) {
            System.out.print(ex.toString());
            return soluong;
        }

    }
    private void btn_xoakhoidanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoakhoidanhsachActionPerformed
        // TODO add your handling code here:
        try{
        String soluongmuonxoa = JOptionPane.showInputDialog(this, "Nhập số lượng cần xóa!");
        if(soluongmuonxoa.equals("")){
            JOptionPane.showMessageDialog(null, "Nhập kiểu số", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }else if (Quanlykho.loi_kytu(soluongmuonxoa) == false) {
            JOptionPane.showMessageDialog(null, "Nhập kiểu số", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }else {
        try {
                int soluongxoa = Integer.parseInt(soluongmuonxoa);
                Connect a = new Connect();
                Connection conn = a.getConnection();
                int Row = tb_danhsachdagoi.getSelectedRow();
                int maban = Integer.parseInt(lb_ban.getText());
                String mabanh = (String) tb_danhsachdagoi.getValueAt(Row, 3);
                int soluongdadat = (int) tb_danhsachdagoi.getValueAt(Row, 1);
                if (JOptionPane.showConfirmDialog(this, "Xóa bánh?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    Statement dd = conn.createStatement();

                    if (soluongxoa == soluongdadat) {

                        dd.executeUpdate("delete from ban_banh where mabanh like '" + mabanh + "' and soban = " + maban + "");
                        int soluongupdate = soluongdadat + soluongne(mabanh);
                        dd.executeUpdate("update banh set soluongconlai = " + soluongupdate + " where mabanh = '" + mabanh + "'  ");
                        DefaultTableModel danhsachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
                        danhsachdagoi.setRowCount(0);
                        Tai_Dagoi(maban);

                    } else if (soluongxoa > soluongdadat) {
                        JOptionPane.showMessageDialog(null, "Số lượng xóa nhiều hơn số lượng đặt!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else if (soluongxoa < soluongdadat) {
                        int sldatconlai = soluongdadat - soluongxoa;
                        int slconlai = soluongxoa + soluongne(mabanh);
                        dd.executeUpdate("update ban_banh set soluong = " + sldatconlai + " where mabanh = '" + mabanh + "' and soban = " + maban + "");
                        dd.executeUpdate("update banh set soluongconlai = " + slconlai + " where mabanh = '" + mabanh + "'");
                        DefaultTableModel danhsachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
                        danhsachdagoi.setRowCount(0);
                        Tai_Dagoi(maban);

                    }
                    if (Float.parseFloat(txt_sotienthanhtoan.getText()) == 0) {
                        dd.executeUpdate("delete from ban_banh where soban =" + maban);
                        dd.executeUpdate("update ban set tinhtrang = N'TRỐNG' where soban =" + maban);
                        DefaultTableModel danhsachban = (DefaultTableModel) tb_chonban.getModel();
                        danhsachban.setRowCount(0);
                        Tai_DS_Ban();
                    } else if (Float.parseFloat(txt_sotienthanhtoan.getText()) != 0) {
                        btn_xoakhoidanhsach.setEnabled(true);
                    }
                }else{
                    
                }
            } catch (Exception ex) {
                System.out.print(ex.toString());
                JOptionPane.showMessageDialog(null, "Chưa chọn trong danh sách", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
        }catch(Exception ex){}
    }//GEN-LAST:event_btn_xoakhoidanhsachActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        int Row = tb_chonban.getSelectedRow();
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            int maban = Integer.parseInt(lb_ban.getText());
//            Statement dd = conn.createStatement();
//            dd.executeUpdate("delete from ban_banh where soban = " + maban);
            PreparedStatement pr = conn.prepareStatement("delete from ban_banh where soban =" + maban);
            PreparedStatement pr2 = conn.prepareStatement("update ban set tinhtrang = N'TRỐNG' where soban =" + maban);
            pr.executeUpdate();
            pr2.executeUpdate();
            tb_chonban.setValueAt("TRỐNG", Row, 1);
            DefaultTableModel danhsachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
            danhsachdagoi.setRowCount(0);
            Tai_Dagoi(maban);
            txt_sotienthanhtoan.setText("");
            txt_sotiennhan.setText("");
            txt_sotienthua.setText("");
            lb_ban.setText("0");
            JOptionPane.showMessageDialog(null, "Đã thanh toán thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            btn_lammoi.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chưa có dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }

    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:

        try {
            int maban = Integer.parseInt(lb_ban.getText());

            DefaultTableModel danhsachdagoi = (DefaultTableModel) tb_danhsachdagoi.getModel();
            danhsachdagoi.setRowCount(0);
            Tai_Dagoi(maban);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chưa có dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_hoantat;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_quanlykho;
    private javax.swing.JButton btn_quanlytaikhoan;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_trangchinh;
    private javax.swing.JButton btn_xoakhoidanhsach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lb_ban;
    private javax.swing.JLabel lb_banh;
    private javax.swing.JLabel lb_maban;
    private javax.swing.JSpinner spinner_soluong1;
    private javax.swing.JTable tb_chonban;
    private javax.swing.JTable tb_danhsachdagoi;
    private javax.swing.JTable tb_goimon;
    private javax.swing.JLabel txt_soluongconlai;
    private javax.swing.JTextField txt_sotiennhan;
    private javax.swing.JTextField txt_sotienthanhtoan;
    private javax.swing.JTextField txt_sotienthua;
    private javax.swing.JTextField txt_tenbanh;
    // End of variables declaration//GEN-END:variables
}
