/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm_quanly_cuahangbanh;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lyhoa
 */
public class Quanlytaikhoan extends javax.swing.JFrame {

    /**
     * Creates new form Quanlytaikhoan
     */
    public Quanlytaikhoan() {
        initComponents();
        DS_taikhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_themtaikhoanmoi = new javax.swing.JButton();
        btn_chinhsua = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_kichhoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhsachtaikhoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tennhanvien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_idnhanvien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_xoataikhoan1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_chucvu = new javax.swing.JComboBox<>();
        txt_matkhau = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_trangchinh = new javax.swing.JButton();
        btn_quanlykho = new javax.swing.JButton();

        jLabel6.setText("ID nhân viên:");

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phần mềm quản lý bán hàng cửa hàng bánh ngọt");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-management-48.png"))); // NOI18N
        jLabel5.setText("QUẢN LÝ TÀI KHOẢN");
        jLabel5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel5InputMethodTextChanged(evt);
            }
        });

        btn_themtaikhoanmoi.setBackground(java.awt.Color.lightGray);
        btn_themtaikhoanmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-update-left-rotation-24.png"))); // NOI18N
        btn_themtaikhoanmoi.setText("Clear form");
        btn_themtaikhoanmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themtaikhoanmoiActionPerformed(evt);
            }
        });

        btn_chinhsua.setBackground(java.awt.Color.lightGray);
        btn_chinhsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-edit-24.png"))); // NOI18N
        btn_chinhsua.setText("Chỉnh sửa");
        btn_chinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chinhsuaActionPerformed(evt);
            }
        });

        btn_luu.setBackground(java.awt.Color.lightGray);
        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-add-user-male-24.png"))); // NOI18N
        btn_luu.setText("Thêm tài khoản");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_kichhoat.setBackground(java.awt.Color.lightGray);
        btn_kichhoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-check-all-24.png"))); // NOI18N
        btn_kichhoat.setText("Kích hoạt");
        btn_kichhoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kichhoatActionPerformed(evt);
            }
        });

        tb_danhsachtaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên", "ID", "Chức vụ", "Tình trạng"
            }
        ));
        tb_danhsachtaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhsachtaikhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_danhsachtaikhoan);
        if (tb_danhsachtaikhoan.getColumnModel().getColumnCount() > 0) {
            tb_danhsachtaikhoan.getColumnModel().getColumn(0).setPreferredWidth(200);
            tb_danhsachtaikhoan.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Thông tin tài khoản");

        jLabel3.setText("Tên nhân viên:");

        jLabel4.setText("ID nhân viên:");

        jLabel7.setText("Mật khẩu");

        btn_xoataikhoan1.setBackground(java.awt.Color.lightGray);
        btn_xoataikhoan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-delete-bin-24.png"))); // NOI18N
        btn_xoataikhoan1.setText("Xóa tài khoản");
        btn_xoataikhoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoataikhoan1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Chức vụ:");

        cb_chucvu.setBackground(java.awt.Color.lightGray);
        cb_chucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn--", "Nhân viên", "Quản lý" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Danh sách tài khoản");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btn_trangchinh.setBackground(new java.awt.Color(255, 255, 255));
        btn_trangchinh.setForeground(new java.awt.Color(0, 0, 0));
        btn_trangchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-home-24.png"))); // NOI18N
        btn_trangchinh.setText("Trang chính");
        btn_trangchinh.setFocusable(false);
        btn_trangchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trangchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trangchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trangchinh);

        btn_quanlykho.setBackground(new java.awt.Color(255, 255, 255));
        btn_quanlykho.setForeground(new java.awt.Color(0, 0, 0));
        btn_quanlykho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-warehouse-24.png"))); // NOI18N
        btn_quanlykho.setText("Quản lý kho");
        btn_quanlykho.setFocusable(false);
        btn_quanlykho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanlykho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanlykho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlykhoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanlykho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_kichhoat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_chinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoataikhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_idnhanvien, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_tennhanvien)
                                        .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_themtaikhoanmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(334, 334, 334))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_idnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_themtaikhoanmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cb_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_chinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoataikhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_kichhoat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void DS_taikhoan(){
        DefaultTableModel danhsachtaikhoan = (DefaultTableModel)tb_danhsachtaikhoan.getModel();
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("Select tennhanvien, idnhanvien,tinhtrang,chucvu from taikhoan");
                 while(kq.next()){
                    String tennhanvien = kq.getString(1);
                    String idnhanvien =kq.getString(2);
                    String tinhtrang = kq.getString(3);
                    String chucvu = kq.getString(4);
                    danhsachtaikhoan.addRow(new Object[]{tennhanvien, idnhanvien,chucvu,tinhtrang});
                }
                
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
    }
    public boolean loi_kytu_tennhanvien (String chuoi){
        boolean kt =false;
        if(chuoi.length()>50){
            kt = false;
            return kt;
        }else{
            kt=true;
            return kt;
        }
    }
    public boolean loi_kytu (String chuoi){
        boolean kt =false;
        if(chuoi.length()>5||chuoi.length()<5){
            kt = false;
            return kt;
        }else{
            kt=true;
            return kt;
        }
    }
    public boolean loi_trungmaID (String chuoi){
        boolean kt =false;
        String maID="";
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("Select idnhanvien from taikhoan where idnhanvien = "+chuoi+"");
                 while(kq.next()){
                     maID = kq.getString(1);
                }
                
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
        if(maID.equals("")){
            kt = true;
            return kt;
            
        }else{
            kt=false;
            return kt;
        }
    }
    private void jLabel5InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel5InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5InputMethodTextChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    Quanlytaikhoan.this.setVisible(false);
    new Menu().setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    
    private void btn_chinhsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chinhsuaActionPerformed
        // TODO add your handling code here:
        int Row = tb_danhsachtaikhoan.getSelectedRow();
        if(Row<0){
            JOptionPane.showMessageDialog(null,"Chưa chọn tài khoản trong danh sách!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
        String tennhanvien= txt_tennhanvien.getText();
        String idnhanvien= txt_idnhanvien.getText();
        String matkhau= txt_matkhau.getText();
        String chucvu =cb_chucvu.getSelectedItem().toString();
        
        if(tennhanvien.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập tên nhân viên!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu_tennhanvien (tennhanvien)==false){
            JOptionPane.showMessageDialog(null,"Nhập tên nhân viên không quá 50 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(idnhanvien.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập ID nhân viên!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(idnhanvien)==false){
            JOptionPane.showMessageDialog(null,"Nhập ID nhân viên 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(matkhau.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập mật khẩu!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(matkhau)==false){
            JOptionPane.showMessageDialog(null,"Nhập mật khẩu 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(chucvu.equals("--Chọn--")){
            JOptionPane.showMessageDialog(null,"Chưa chọn chức vụ!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            
            if (JOptionPane.showConfirmDialog(this, "Chỉnh sửa tài khoản?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            if (conn!=null){
                Statement dd = conn.createStatement();            
                dd.executeUpdate("Update taikhoan set tennhanvien = N'"+tennhanvien+"',idnhanvien = '"+idnhanvien+"', matkhau = "+matkhau+",chucvu = N'"+chucvu+"', tinhtrang = N'Not Active' where idnhanvien = '"+idnhanvien+"'     ");
                JOptionPane.showMessageDialog(null,"Chỉnh sửa tài khoản thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel danhsachtaikhoan = (DefaultTableModel)tb_danhsachtaikhoan.getModel();
                danhsachtaikhoan.setRowCount(0);
                txt_tennhanvien.setText("");
                txt_idnhanvien.setText("");
                txt_matkhau.setText("");
                cb_chucvu.setSelectedItem("--Chọn--");
                DS_taikhoan();
            }
            }     
        }catch(Exception ex){
            System.out.print(ex);
            JOptionPane.showMessageDialog(null,"Chỉnh sửa không thành công!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        }
        }
    }//GEN-LAST:event_btn_chinhsuaActionPerformed

    private void btn_themtaikhoanmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themtaikhoanmoiActionPerformed
        // TODO add your handling code here:
        txt_tennhanvien.setText("");
        txt_idnhanvien.setText("");
        txt_matkhau.setText("");
        cb_chucvu.setSelectedItem("--Chọn--");
    }//GEN-LAST:event_btn_themtaikhoanmoiActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        String tennhanvien= txt_tennhanvien.getText();
        String idnhanvien= txt_idnhanvien.getText();
        String matkhau= txt_matkhau.getText();
        String chucvu =cb_chucvu.getSelectedItem().toString();
        
        if(tennhanvien.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập tên nhân viên!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu_tennhanvien (tennhanvien)==false){
            JOptionPane.showMessageDialog(null,"Nhập tên nhân viên không quá 50 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(idnhanvien.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập ID nhân viên!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(idnhanvien)==false){
            JOptionPane.showMessageDialog(null,"Nhập ID nhân viên 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_trungmaID (idnhanvien)==false){
            JOptionPane.showMessageDialog(null,"ID nhân viên đã trùng!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(matkhau.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập mật khẩu!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(matkhau)==false){
            JOptionPane.showMessageDialog(null,"Nhập mật khẩu 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(chucvu.equals("--Chọn--")){
            JOptionPane.showMessageDialog(null,"Chưa chọn chức vụ!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            
            if (JOptionPane.showConfirmDialog(this, "Tạo thêm tài khoản mới?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            if (conn!=null){
                Statement dd = conn.createStatement();            
                dd.executeUpdate("insert into taikhoan (tennhanvien,idnhanvien,matkhau,tinhtrang,chucvu) values ( N'"+tennhanvien+"','"+idnhanvien+"','"+matkhau+"','Not Active',N'"+chucvu+"'  )   ");
                JOptionPane.showMessageDialog(null,"Thêm tài khoản mới thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel danhsachtaikhoan = (DefaultTableModel)tb_danhsachtaikhoan.getModel();
                danhsachtaikhoan.setRowCount(0);
                txt_tennhanvien.setText("");
                txt_idnhanvien.setText("");
                txt_matkhau.setText("");
                cb_chucvu.setSelectedItem("--Chọn--");
                DS_taikhoan();
            }
            }
        }catch(Exception ex){
            System.out.print(ex);
            JOptionPane.showMessageDialog(null,"Thêm mới không thành công!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void tb_danhsachtaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhsachtaikhoanMouseClicked
        // TODO add your handling code here:
        int Row = tb_danhsachtaikhoan.getSelectedRow();
        String idnhanvien = (String) tb_danhsachtaikhoan.getValueAt(Row,1);
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("Select tennhanvien,idnhanvien,matkhau,chucvu from taikhoan where idnhanvien = "+idnhanvien+"");
                 while(kq.next()){
                    
                    txt_tennhanvien.setText(kq.getString(1));
                    txt_idnhanvien.setText(kq.getString(2));
                    txt_matkhau.setText(kq.getString(3));
                    cb_chucvu.setSelectedItem(kq.getString(4));
                    
                    
                }
                
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
    }//GEN-LAST:event_tb_danhsachtaikhoanMouseClicked

    private void btn_xoataikhoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoataikhoan1ActionPerformed
        // TODO add your handling code here:
        try{
        int Row = tb_danhsachtaikhoan.getSelectedRow();
        String idnhanvien = (String) tb_danhsachtaikhoan.getValueAt(Row,1);
        
            try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (JOptionPane.showConfirmDialog(this, "Xóa tài khoản khỏi phần mềm?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
               if (conn!=null){
                Statement dd = conn.createStatement();            
                dd.executeUpdate("Delete taikhoan where idnhanvien = '"+idnhanvien+"'     ");
                JOptionPane.showMessageDialog(null,"Xóa tài khoản thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel danhsachtaikhoan = (DefaultTableModel)tb_danhsachtaikhoan.getModel();
                danhsachtaikhoan.setRowCount(0);
                txt_tennhanvien.setText("");
                txt_idnhanvien.setText("");
                txt_matkhau.setText("");
                cb_chucvu.setSelectedItem("--Chọn--");
                DS_taikhoan();
            }
            }
            
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
            JOptionPane.showMessageDialog(null,"Xóa không thành công!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Chưa chọn tài khoản trong danh sách!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoataikhoan1ActionPerformed

    private void btn_kichhoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kichhoatActionPerformed
        // TODO add your handling code here:
        int Row = tb_danhsachtaikhoan.getSelectedRow();
        if(Row<0){
            JOptionPane.showMessageDialog(null,"Chưa chọn tài khoản trong danh sách!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            String idnhanvien = (String) tb_danhsachtaikhoan.getValueAt(Row,1);
            try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            
            if (JOptionPane.showConfirmDialog(this, "Kích hoạt tài khoản?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            if (conn!=null){
                Statement dd = conn.createStatement();            
                dd.executeUpdate("Update taikhoan set tinhtrang = 'Active' where idnhanvien = '"+idnhanvien+"'     ");
                JOptionPane.showMessageDialog(null,"Kích hoạt tài khoản thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel danhsachtaikhoan = (DefaultTableModel)tb_danhsachtaikhoan.getModel();
                danhsachtaikhoan.setRowCount(0);
                txt_tennhanvien.setText("");
                txt_idnhanvien.setText("");
                txt_matkhau.setText("");
                cb_chucvu.setSelectedItem("--Chọn--");
                DS_taikhoan();
            }
            }       
        }catch(Exception ex){
            System.out.print(ex);
            JOptionPane.showMessageDialog(null,"Kích hoạt tài khoản không thành công!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        
        }
    }//GEN-LAST:event_btn_kichhoatActionPerformed

    private void btn_trangchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchinhActionPerformed
        // TODO add your handling code here:
        Quanlytaikhoan.this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_btn_trangchinhActionPerformed

    private void btn_quanlykhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlykhoActionPerformed
        // TODO add your handling code here:

        loi_chucvu2();
    }//GEN-LAST:event_btn_quanlykhoActionPerformed

     public void loi_chucvu2() {
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn != null) {
                Statement dd = conn.createStatement();
                ResultSet kq = dd.executeQuery("Select chucvu,tinhtrang from taikhoan where idnhanvien = '" + DangNhap.ID + "' ");
                while (kq.next()) {
                    String chucvu = kq.getString(1);
                    String tinhtrang = kq.getString(2);

                    if (chucvu.equals("Quản lý") && tinhtrang.trim().equals("Active")) {
                        Quanlytaikhoan.this.setVisible(false);
                        new Quanlykho().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Phải đăng nhập bằng tài khoản quản lý!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlytaikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chinhsua;
    private javax.swing.JButton btn_kichhoat;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_quanlykho;
    private javax.swing.JButton btn_themtaikhoanmoi;
    private javax.swing.JButton btn_trangchinh;
    private javax.swing.JButton btn_xoataikhoan1;
    private javax.swing.JComboBox<String> cb_chucvu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tb_danhsachtaikhoan;
    private javax.swing.JTextField txt_idnhanvien;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JTextField txt_tennhanvien;
    // End of variables declaration//GEN-END:variables
}
