/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm_quanly_cuahangbanh;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lyhoa
 */
public class Quenmatkhau extends javax.swing.JFrame {

    /**
     * Creates new form Quenmatkhau
     */
    public Quenmatkhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textbox_TaoTaiKhoan_IDnhanvien = new javax.swing.JTextField();
        textbox_TaoTaiKhoan_NhapLaiMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_TroVeTrangDangNhap = new javax.swing.JLabel();
        textbox_TaoTaiKhoan_MatKhau = new javax.swing.JPasswordField();
        button_TaoLaiMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textbox_TaoTaiKhoan_NhapLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_TaoTaiKhoan_NhapLaiMatKhauActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-account-48.png"))); // NOI18N
        jLabel1.setText("QUÊN TÀI KHOẢN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-test-account-24.png"))); // NOI18N
        jLabel2.setText("ID ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-key-2-24.png"))); // NOI18N
        jLabel4.setText("Mật khẩu");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-key-2-24.png"))); // NOI18N
        jLabel6.setText("Nhập lại mật khẩu");

        label_TroVeTrangDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-go-back-24.png"))); // NOI18N
        label_TroVeTrangDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_TroVeTrangDangNhapMouseClicked(evt);
            }
        });

        button_TaoLaiMatKhau.setBackground(java.awt.Color.lightGray);
        button_TaoLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm_quanly_cuahangbanh/image/icons8-update-24.png"))); // NOI18N
        button_TaoLaiMatKhau.setText("Đổi Mật Khẩu");
        button_TaoLaiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_TaoLaiMatKhauMouseClicked(evt);
            }
        });
        button_TaoLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TaoLaiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textbox_TaoTaiKhoan_IDnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(textbox_TaoTaiKhoan_MatKhau)))
                    .addComponent(button_TaoLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_TroVeTrangDangNhap)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textbox_TaoTaiKhoan_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textbox_TaoTaiKhoan_IDnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textbox_TaoTaiKhoan_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textbox_TaoTaiKhoan_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_TaoLaiMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_TroVeTrangDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean loi_kytu (String chuoi){
        boolean kt =false;
        if(chuoi.length()>5||chuoi.length()<5){
            kt = false;
            return kt;
        }else{
            kt=true;
            return kt;
        }
    }
    public boolean loi_id (String chuoi){
        boolean kt =false;
        String id="";
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("Select idnhanvien from taikhoan where idnhanvien = '"+chuoi+"'");
                 while(kq.next()){
                     id = kq.getString(1);
                }
                
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
        if(id.equals("")){
            kt = false;
            return kt;
            
        }else{
            kt=true;
            return kt;
        }
    }
    public void DoiMatKhau(){
        String idnhanvien = textbox_TaoTaiKhoan_IDnhanvien.getText();
        String matkhau = textbox_TaoTaiKhoan_MatKhau.getText();
        String matkhau2 = textbox_TaoTaiKhoan_NhapLaiMatKhau.getText();
        
        if(idnhanvien.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập ID nhân viên!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(idnhanvien)==false){
            JOptionPane.showMessageDialog(null,"Nhập ID nhân viên 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(matkhau.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập mật khẩu!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(matkhau)==false){
            JOptionPane.showMessageDialog(null,"Nhập mật khẩu 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(matkhau2.equals("")){
            JOptionPane.showMessageDialog(null,"Chưa nhập lại mật khẩu!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(loi_kytu(matkhau2)==false){
            JOptionPane.showMessageDialog(null,"Nhập lại mật khẩu 5 ký tự!","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(matkhau2.equals(matkhau)==false){
            JOptionPane.showMessageDialog(null, "Mật khẩu không trùng khớp!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }else if(loi_id (idnhanvien)==false){
            JOptionPane.showMessageDialog(null, "ID nhân viên không có trong CSDL!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Connect a = new Connect();
                Connection conn = a.getConnection();
                Statement da = conn.createStatement();  
                da.executeUpdate("update taikhoan set matkhau = '"+matkhau2+"' ,tinhtrang = 'Not Active' where idnhanvien = '" +idnhanvien+"'");                        
                JOptionPane.showMessageDialog(null, "Mật khẩu đã đổi, hiện không thể đăng nhập bằng tài khoản này! \n"
                                + "Liên hệ với quản lý để kich hoạt tài khoản!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Thông báo", JOptionPane.ERROR_MESSAGE);
            }  
        }
    }
    private void label_TroVeTrangDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_TroVeTrangDangNhapMouseClicked
        // TODO add your handling code here:
        Quenmatkhau.this.setVisible(false);
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_label_TroVeTrangDangNhapMouseClicked

    private void button_TaoLaiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_TaoLaiMatKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_TaoLaiMatKhauMouseClicked

    private void button_TaoLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TaoLaiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau();
       
    }//GEN-LAST:event_button_TaoLaiMatKhauActionPerformed

    private void textbox_TaoTaiKhoan_NhapLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_TaoTaiKhoan_NhapLaiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_TaoTaiKhoan_NhapLaiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quenmatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quenmatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quenmatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quenmatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quenmatkhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_TaoLaiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_TroVeTrangDangNhap;
    private javax.swing.JTextField textbox_TaoTaiKhoan_IDnhanvien;
    private javax.swing.JPasswordField textbox_TaoTaiKhoan_MatKhau;
    private javax.swing.JPasswordField textbox_TaoTaiKhoan_NhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables
}
